name: totp_generator
description: A flexible and easy-to-use Time-based One-Time Password (TOTP) generator for Dart and Flutter applications. This package supports multiple hash algorithms and secret encodings, making it compatible with most TOTP implementations.
version: 1.0.0
repository: https://github.com/AscEmon/totp_generator

environment:
  sdk: ^3.7.2

dependencies:
  crypto: ^3.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
